sudo: required
services:
  - docker

before_install:
  - docker build -t sarodesparsh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarodesparsh/docker-react npm run test -- --coverage
